#https://devops4solutions.com/deploy-a-tomcat-application-using-docker-compose/
version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dd'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'tuser1'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'tuser1!7D'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'VLpk8QtBsQz5vtk'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8514:8514'
    expose:
      # Opens port 3306 on the container
      - '8514'
      # Where our data will be persisted
    volumes:
      - /var/lib/mysql
  
  web:
    depends_on: 
      - db
    image: tomcat
    ports:
      - "8087:8087"

# Names our volume
#volumes:
#  db-data: