version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dd'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'acp4pogynvaeidfj'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'jc31d2qyy7h9jv5jn1u9uosjksxzaizw'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '!qaz@wsx'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8514:8514'
    expose:
      # Opens port 3306 on the container
      - '8514'
      # Where our data will be persisted
    volumes:
      - /var/lib/mysql
# Names our volume
#volumes:
#  db-data: