version: '3.3'

services:


  mysql-container:
    image: mariadb:10.1
    #restart: always
    environment:
      MYSQL_DATABASE: dd
      # So you don't have to use root, but you can if you like
      MYSQL_USER: tuser17
      # You can use whatever password you like
      MYSQL_PASSWORD: VLpk8QtBsQz5vtk
      # Password for root access
      MYSQL_ROOT_PASSWORD: tuser1!7D
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    #expose:
      # Opens port 3306 on the container
      #- '3306'
      # Where our data will be persisted
    volumes:
      - /var/lib/mysql/

  tomcat-container:
    build:
      context: .
    volumes:
      - .:/tmp/
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"